"""
Django settings for Fast-Django-Bridge project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-17%9*_qo!=l#gv8+zoq@h&7tqd8&sq6#u^7r%@jng34l@v&e+j"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", True) != "False"
# DEBUG = True

ALLOWED_HOSTS = [
    '*'
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',

    # django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # apps
    "account",
    "core",

    # third party
    # "corsheaders",
    # "django_filters",
    "ckeditor",
    "rosetta",
    # "django_countries",
    'parler',
    # 'celery',
    # 'django_celery_results',
    # 'django_celery_beat',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "corsheaders.middleware.CorsMiddleware",  # cors
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'core.middleware.SetDefaultLanguageMiddleware',
]

ROOT_URLCONF = "django_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": os.path.join(BASE_DIR, 'templates'),
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_app.wsgi.application"

CELERY_RESULT_BACKEND = 'django-db'
CELERY_BROKER_URL = 'redis://redis:6379/0'
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": os.environ.get("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATIC_URL = "/static/"
if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, "static")


AUTH_USER_MODEL = "account.MyUser"


# Allow all origins (not recommended for production)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3000",
    # "https://api.alisontravelgroup.com",
    # "https://alison-travel-integration-v.vercel.app",
    # "http://159.223.19.108",
]
# CORS_ALLOW_ALL_ORIGINS = True

# Allow all headers (again, not recommended)
CORS_ALLOWED_HEADERS = ["*"]
CORS_ALLOWED_METHODS = ["*"]
CORS_EXPOSED_HEADERS = ["Content-Length", "X-My-Header"]
CORS_PREFLIGHT_MAX_AGE = 86400

TRUST_DOWNSTREAM_PROXY = False

CSRF_TRUSTED_ORIGINS = [
    # 'https://api.alisontravelgroup.com',
    # 'http://159.223.19.108',
    # "http://localhost:8000",
    # "http://127.0.0.1:8000"
]

CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": "200",
    },
}

# language
PARLER_DEFAULT_LANGUAGE_CODE = 'en'

PARLER_LANGUAGES = {
    None: (
        {'code': 'en',},
        {'code': 'az',},
        {'code': 'ru',},
    ),
    'default': {
        'fallbacks': ['en'],
        'hide_untranslated': False,
    }
}

LANGUAGE_CODE = 'en'

# LANGUAGES = (
#     ('en', _('English')),
#     ('az', _('Azerbaijani')),
#     ('ru', _('Russian')),
# )

# LOCALE_PATHS = (
#     os.path.join(BASE_DIR, 'locale'),
# )

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_TZ = True

USE_L10N = True

JAZZMIN_SETTINGS = {
    "site_logo": "admin/img/Fast-Django-Bridge.png",  # Path to your logo file
    "site_icon": "admin/img/Fast-Django-Bridge.png",  # Path to your favicon file
    "welcome_sign": "Fast-Django-Bridge Admin Panel",
    "copyright": "WeMark",
    "custom_css": "admin/css/admin_custom.css",  # Custom CSS file for resizing
    "order_with_respect_to": ["core", "account"],  # Apps ordering
    "hide_recent_actions": True,
        "topmenu_links": [
        {"name": "Go to Website", "url": "https://Fast-Django-Bridge.com/", "permissions": ["auth.view_user"]},
    ],
}

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('MAIL_SERVER')
# EMAIL_HOST_USER = os.getenv('MAIL_USERNAME')
# EMAIL_HOST_PASSWORD = os.getenv('MAIL_PASSWORD')
# EMAIL_PORT = int(os.getenv('MAIL_PORT', 465))
# EMAIL_FROM = os.getenv('MAIL_FROM')
# EMAIL_USE_TLS = True
